---
driver:
  name: docker
  hostname: java.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: java
  grains:
    noservices: True
  state_top:
    base:
      "*":
        - java
  pillars:
    top.sls:
      base:
        "*":
          - java

verifier:
  name: inspec
  sudo: true


platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

suites:

  - name: openjdk-7
    provisioner:
      pillars-from-files:
        java.sls: tests/pillar/openjdk-7.sls

  - name: openjdk-8
    provisioner:
      pillars-from-files:
        java.sls: tests/pillar/openjdk-8.sls

  - name: openjdk-9
    provisioner:
      pillars-from-files:
        java.sls: tests/pillar/openjdk-9.sls

  - name: openjdk-10
    provisioner:
      pillars-from-files:
        java.sls: tests/pillar/openjdk-10.sls

  - name: oracle-jdk-8
    provisioner:
      pillars-from-files:
        java.sls: tests/pillar/oracle-jdk-8.sls

  - name: oracle-jdk-9
    provisioner:
      pillars-from-files:
        java.sls: tests/pillar/oracle-jdk-9.sls

  - name: oracle-jdk-10
    provisioner:
      pillars-from-files:
        java.sls: tests/pillar/oracle-jdk-10.sls
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125